import type { Metadata } from 'next';
import { Geist, Geist_Mono, Playfair_Display, Jost } from 'next/font/google';
import './globals.css';
import BackgroundVideo from './components/BackGroundVideo';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400'],
});

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
  weight: ['400'],
});

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin'],
  weight: ['400', '500'],
});

export const metadata: Metadata = {
  title: 'Testovoe front Plan9',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${jost.variable} bg-night relative font-sans antialiased`}
      >
        <BackgroundVideo />
        {children}
      </body>
    </html>
  );
}
